const avolittyHasher = require('../src/avolitty-hasher.js')
console.log("Input: avolittyHasher(global, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher(global, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"global\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("global", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(global.clearTimeout, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher(global.clearTimeout, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"global.clearTimeout\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("global.clearTimeout", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(function() {}, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher(function() {}, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"function() {}\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("function() {}", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(function(a) {}, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher(function(a) {}, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"function(a) {}\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("function(a) {}", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(function(a) {return}, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher(function(a) {return}, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"function(a) {return}\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("function(a) {return}", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(function(a) { return}, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher(function(a) { return}, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"function(a) { return}\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("function(a) { return}", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher({}, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher({}, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"{}\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("{}", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher({\"0\": 0}, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher({"0": 0}, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher({\"0\": 1}, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher({"0": 1}, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher([], {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher([], {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"[]\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("[]", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher([0], {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher([0], {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"[0]\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("[0]", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(null, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher(null, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"null\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("null", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(true, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher(true, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"true\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("true", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(false, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher(false, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"false\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("false", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(Infinity, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher(Infinity, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"Infinity\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("Infinity", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(-Infinity, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher(-Infinity, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"-Infinity\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("-Infinity", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(NaN, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher(NaN, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"NaN\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("NaN", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(0, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher(0, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"0\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("0", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"01\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("01", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(1, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher(1, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"1\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("1", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"10\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("10", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(void 0, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher(void 0, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"void 0\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("void 0", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(undefined, {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher(undefined, {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"undefined\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("undefined", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"🥑\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("🥑", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"🥑🥑\", {\"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher("🥑🥑", {"outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher({\"3\": \"🥑\", \"2\": \"🥑\", \"1\": \"🥑\"}, {\"ignoreObjectKeySortOrder\": false, \"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher({"3": "🥑", "2": "🥑", "1": "🥑"}, {"ignoreObjectKeySortOrder": false, "outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher({\"3\": \"🥑\", \"2\": \"🥑\", \"1\": \"🥑\"}, {\"ignoreObjectKeySortOrder\": true, \"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher({"3": "🥑", "2": "🥑", "1": "🥑"}, {"ignoreObjectKeySortOrder": true, "outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher({\"1\": \"🥑\", \"2\": \"🥑\", \"3\": \"🥑\"}, {\"ignoreObjectKeySortOrder\": true, \"outputLength\": 8})")
console.log("Output: \"" + avolittyHasher({"1": "🥑", "2": "🥑", "3": "🥑"}, {"ignoreObjectKeySortOrder": true, "outputLength": 8}) + "\"\n")
console.log("Input: avolittyHasher(\"🥑\", {\"outputLength\": 16})")
console.log("Output: \"" + avolittyHasher("🥑", {"outputLength": 16}) + "\"\n")
console.log("Input: avolittyHasher(\"🥑\", {\"outputLength\": 32})")
console.log("Output: \"" + avolittyHasher("🥑", {"outputLength": 32}) + "\"\n")
console.log("Input: avolittyHasher(\"🥑\", {\"outputLength\": 64})")
console.log("Output: \"" + avolittyHasher("🥑", {"outputLength": 64}) + "\"\n")
console.log("Input: avolittyHasher(\"🥑\", {\"outputLength\": 128})")
console.log("Output: \"" + avolittyHasher("🥑", {"outputLength": 128}) + "\"\n")

