const avolittyHasher = require('./avolitty-hasher.js')
console.log("Input: global")
console.log("Output: \"" + avolittyHasher(global) + "\"\n")
console.log("Input: \"global\"")
console.log("Output: \"" + avolittyHasher("global") + "\"\n")
console.log("Input: global.clearTimeout")
console.log("Output: \"" + avolittyHasher(global.clearTimeout) + "\"\n")
console.log("Input: \"global.clearTimeout\"")
console.log("Output: \"" + avolittyHasher("global.clearTimeout") + "\"\n")
console.log("Input: function() {}")
console.log("Output: \"" + avolittyHasher(function() {}) + "\"\n")
console.log("Input: \"function() {}\"")
console.log("Output: \"" + avolittyHasher("function() {}") + "\"\n")
console.log("Input: function(a) {}")
console.log("Output: \"" + avolittyHasher(function(a) {}) + "\"\n")
console.log("Input: \"function(a) {}\"")
console.log("Output: \"" + avolittyHasher("function(a) {}") + "\"\n")
console.log("Input: function(a) {return}")
console.log("Output: \"" + avolittyHasher(function(a) {return}) + "\"\n")
console.log("Input: \"function(a) {return}\"")
console.log("Output: \"" + avolittyHasher("function(a) {return}") + "\"\n")
console.log("Input: function(a) { return}")
console.log("Output: \"" + avolittyHasher(function(a) { return}) + "\"\n")
console.log("Input: \"function(a) { return}\"")
console.log("Output: \"" + avolittyHasher("function(a) { return}") + "\"\n")
console.log("Input: {}")
console.log("Output: \"" + avolittyHasher({}) + "\"\n")
console.log("Input: \"{}\"")
console.log("Output: \"" + avolittyHasher("{}") + "\"\n")
console.log("Input: {\"0\": 0}")
console.log("Output: \"" + avolittyHasher({"0": 0}) + "\"\n")
console.log("Input: {\"0\": 1}")
console.log("Output: \"" + avolittyHasher({"0": 1}) + "\"\n")
console.log("Input: []")
console.log("Output: \"" + avolittyHasher([]) + "\"\n")
console.log("Input: \"[]\"")
console.log("Output: \"" + avolittyHasher("[]") + "\"\n")
console.log("Input: [0]")
console.log("Output: \"" + avolittyHasher([0]) + "\"\n")
console.log("Input: \"[0]\"")
console.log("Output: \"" + avolittyHasher("[0]") + "\"\n")
console.log("Input: null")
console.log("Output: \"" + avolittyHasher(null) + "\"\n")
console.log("Input: \"null\"")
console.log("Output: \"" + avolittyHasher("null") + "\"\n")
console.log("Input: true")
console.log("Output: \"" + avolittyHasher(true) + "\"\n")
console.log("Input: \"true\"")
console.log("Output: \"" + avolittyHasher("true") + "\"\n")
console.log("Input: false")
console.log("Output: \"" + avolittyHasher(false) + "\"\n")
console.log("Input: \"false\"")
console.log("Output: \"" + avolittyHasher("false") + "\"\n")
console.log("Input: Infinity")
console.log("Output: \"" + avolittyHasher(Infinity) + "\"\n")
console.log("Input: \"Infinity\"")
console.log("Output: \"" + avolittyHasher("Infinity") + "\"\n")
console.log("Input: -Infinity")
console.log("Output: \"" + avolittyHasher(-Infinity) + "\"\n")
console.log("Input: \"-Infinity\"")
console.log("Output: \"" + avolittyHasher("-Infinity") + "\"\n")
console.log("Input: NaN")
console.log("Output: \"" + avolittyHasher(NaN) + "\"\n")
console.log("Input: \"NaN\"")
console.log("Output: \"" + avolittyHasher("NaN") + "\"\n")
console.log("Input: 0")
console.log("Output: \"" + avolittyHasher(0) + "\"\n")
console.log("Input: \"0\"")
console.log("Output: \"" + avolittyHasher("0") + "\"\n")
console.log("Input: \"01\"")
console.log("Output: \"" + avolittyHasher("01") + "\"\n")
console.log("Input: 1")
console.log("Output: \"" + avolittyHasher(1) + "\"\n")
console.log("Input: \"1\"")
console.log("Output: \"" + avolittyHasher("1") + "\"\n")
console.log("Input: \"10\"")
console.log("Output: \"" + avolittyHasher("10") + "\"\n")
console.log("Input: \"\"")
console.log("Output: \"" + avolittyHasher("") + "\"\n")
console.log("Input: void 0")
console.log("Output: \"" + avolittyHasher(void 0) + "\"\n")
console.log("Input: \"void 0\"")
console.log("Output: \"" + avolittyHasher("void 0") + "\"\n")
console.log("Input: undefined")
console.log("Output: \"" + avolittyHasher(undefined) + "\"\n")
console.log("Input: \"undefined\"")
console.log("Output: \"" + avolittyHasher("undefined") + "\"\n")
console.log("Input: \"🔥\"")
console.log("Output: \"" + avolittyHasher("🔥") + "\"\n")
console.log("Input: \"0🔥\"")
console.log("Output: \"" + avolittyHasher("0🔥") + "\"\n")
console.log("Input: \"🔥0\"")
console.log("Output: \"" + avolittyHasher("🔥0") + "\"\n")
console.log("Input: \"🔥🔥\"")
console.log("Output: \"" + avolittyHasher("🔥🔥") + "\"\n")
